# Generated by Django 4.0.4 on 2022-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
