# Generated by Django 4.0.4 on 2022-05-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0003_rename_password_login_adminpassword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogIn',
        ),
    ]
