# Generated by Django 4.0.4 on 2022-05-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogIn',
        ),
    ]
