# Generated by Django 4.0.4 on 2022-05-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0006_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_username', models.CharField(max_length=50)),
                ('account_password', models.CharField(max_length=50)),
            ],
        ),
    ]
