# Generated by Django 4.0.4 on 2022-05-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0007_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.CharField(blank=True, max_length=50, null=True)),
                ('YourEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('YourPhone', models.IntegerField(blank=True, null=True)),
                ('YourDate', models.IntegerField(blank=True, null=True)),
                ('YourMessage', models.TextField(blank=True, null=True)),
                ('YourDepartment', models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Hepatology', 'Hepatology'), ('Pediatrics', 'Pediatrics'), ('Eya Care', 'Eya Care')], max_length=50, null=True)),
                ('YourDoctor', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
