# Generated by Django 4.0.4 on 2022-05-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0009_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
