# Generated by Django 4.0.4 on 2022-05-22 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0010_messageus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDepartment',
            field=models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Hepatology', 'Hepatology'), ('Pediatrics', 'Pediatrics'), ('Eya Care', 'Eya Care')], max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDoctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourEmail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourMessage',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourPhone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='login',
            name='account_password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='login',
            name='account_username',
            field=models.CharField(max_length=50, verbose_name='UserName'),
        ),
    ]
