# Generated by Django 4.0.4 on 2022-05-22 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0011_alter_appointment_yourdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 4, 17, 25, 611441), null=True, verbose_name='Date'),
        ),
    ]
