# Generated by Django 4.0.4 on 2022-05-22 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0012_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['YourName']},
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'ordering': ['account_username']},
        ),
        migrations.AlterModelOptions(
            name='messageus',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 4, 44, 52, 916806), null=True, verbose_name='Date'),
        ),
    ]
