# Generated by Django 4.0.4 on 2022-05-22 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0013_alter_appointment_options_alter_login_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo_Doctor', models.ImageField(upload_to='photo')),
                ('Name_Doctor', models.CharField(max_length=50)),
                ('Bio_Doctor', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['Name_Doctor'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 5, 4, 44, 59084), null=True, verbose_name='Date'),
        ),
    ]
