# Generated by Django 4.0.4 on 2022-05-22 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0014_doctor_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 5, 50, 44, 756870), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Bio_Doctor',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Name_Doctor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Photo_Doctor',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
