# Generated by Django 4.0.4 on 2022-06-01 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0021_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 1, 12, 37, 12, 30273), null=True, verbose_name='Date'),
        ),
    ]
