# Generated by Django 4.0.4 on 2022-06-01 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0024_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogIn',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 1, 16, 16, 51, 894352), null=True, verbose_name='Date'),
        ),
    ]
