# Generated by Django 4.0.4 on 2022-06-03 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0028_info_delete_messageus_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='place',
            new_name='Place',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 3, 22, 51, 32, 77955), null=True, verbose_name='Date'),
        ),
    ]
