# Generated by Django 4.0.4 on 2022-06-03 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0029_rename_phone_number_info_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Place',
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 3, 23, 0, 57, 43663), null=True, verbose_name='Date'),
        ),
    ]
