# Generated by Django 4.0.3 on 2022-06-27 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0030_remove_info_phone_number_remove_info_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 2, 47, 4, 651263), null=True, verbose_name='Date'),
        ),
    ]
