# Generated by Django 4.0.3 on 2022-07-02 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0041_delete_doctor_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 3, 1, 57, 11, 3588), null=True, verbose_name='Date'),
        ),
    ]
