# Generated by Django 4.0.3 on 2022-07-03 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0042_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 3, 5, 58, 54, 292912), null=True, verbose_name='Date'),
        ),
    ]
