# Generated by Django 4.0.3 on 2022-07-04 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0043_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 4, 3, 5, 7, 535192), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDepartment',
            field=models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Hepatology', 'Hepatology'), ('Pediatrics', 'Pediatrics'), ('Eya Care', 'Eya Care')], max_length=50, null=True),
        ),
    ]
