# Generated by Django 4.0.3 on 2022-07-11 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0044_alter_appointment_yourdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='YourDepartment',
            new_name='Department',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 20, 44, 43, 924930), null=True, verbose_name='Date'),
        ),
    ]
