# Generated by Django 4.0.3 on 2022-07-12 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amgad_app', '0051_alter_appointment_yourdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='YourDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 2, 39, 53, 36767), null=True, verbose_name='Date'),
        ),
    ]
