# Generated by Django 4.0.3 on 2022-06-30 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Father_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Gender', models.CharField(blank=True, max_length=255, null=True)),
                ('Blood_Group', models.CharField(blank=True, max_length=255, null=True)),
                ('Birth_time', models.TimeField(blank=True, null=True)),
                ('Birth_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('No_packets_used', models.IntegerField(blank=True, null=True)),
                ('No_packets_present', models.IntegerField(blank=True, null=True)),
                ('Blood_Group', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(null=True)),
                ('Gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True)),
                ('Birth_Date', models.DateField(blank=True, null=True)),
                ('Death_time', models.TimeField(blank=True, null=True)),
                ('Death_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(max_length=255)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
                ('Salary', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Status_from_Date', models.DateField(blank=True, null=True)),
                ('Status_to_Date', models.DateField(blank=True, null=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True)),
                ('Salary', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Job', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Status_from_Date', models.DateField(blank=True, null=True)),
                ('Status_to_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Num_of_Rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Test_type', models.CharField(blank=True, max_length=255, null=True)),
                ('Cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Bio', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Avilable_or_not', models.CharField(blank=True, choices=[('Avaliable', 'Avaliable'), ('Not_Avilable', 'Not_Avilable')], max_length=255, null=True)),
                ('Cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Num_of_Bed', models.IntegerField(blank=True, null=True)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos_app.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Blood', models.CharField(blank=True, max_length=255, null=True)),
                ('Bio', models.CharField(blank=True, max_length=255, null=True)),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Machiens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Operation_Cost', models.IntegerField(null=False,blank=False,default=0)),
                ('Bed_Cost', models.IntegerField(null=False,blank=False,default=0)),
                ('Service_Cost', models.IntegerField(null=False,blank=False,default=0)),
                ('Medical_Cost', models.IntegerField(null=False,blank=False,default=0)),
                ('Lab_Cost', models.IntegerField(null=False,blank=False,default=0)),
                ('Blood_Cost', models.IntegerField(null=False,blank=False,default=0)),
                ('Total', models.IntegerField(null=False,blank=False,default=0)),
                ('Status', models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=255, null=True)),
                ('Patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hos_app.patient')),
            ],
        ),
    ]
