# Generated by Django 4.0.3 on 2022-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Doctor_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
