# Generated by Django 4.0.3 on 2022-07-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0002_remove_patient_doctor_id_doctor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Image',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
