# Generated by Django 4.0.3 on 2022-07-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0003_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Salary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
