# Generated by Django 4.0.3 on 2022-07-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0004_alter_doctor_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
