# Generated by Django 4.0.3 on 2022-07-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0005_alter_doctor_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
